version: "3"

services:
  web:
    container_name: web
    build:
      context: .
      dockerfile: ./apps/web/Dockerfile
    restart: always
    ports:
      - 3000:3000
    networks:
      - chat
    environment:
      - CONNECT_URL=${CONNECT_URL}

  api:
    container_name: api
    build:
      context: .
      dockerfile: ./apps/api/Dockerfile
    restart: always
    ports:
      - 8080:8080
    networks:
      - chat
    environment:
      - PORT=${PORT}
      - DATABASE_URL=${DATABASE_URL}
      - SERVER_SECRET_ALGORITHM=${SERVER_SECRET_ALGORITHM}
      - ACCESS_TOKEN_EXPIRATION_TIME=${ACCESS_TOKEN_EXPIRATION_TIME}
      - REFRESH_TOKEN_EXPIRATION_TIME=${REFRESH_TOKEN_EXPIRATION_TIME}
      - ACCESS_TOKEN_SECRET=${ACCESS_TOKEN_SECRET}
      - REFRESH_TOKEN_SECRET=${REFRESH_TOKEN_SECRET}

networks:
  chat:
    external: true
